### ISSUE TITLE
Hi, is this app still working?

### ISSUE THREAD

**Issue by jakubkrapiec** [rakeshgirase/app-release-manager#2]
I tried to integrate it to my CI, but `java -jar release-manager-1.0.jar -key "my-api-key.json" -apk "/build/app/outputs/bundle/release/app.aab" -track "internal" -name "MyApp" -notes "test"` shows
```
Loading account credentials...
true
Loading apk file information...
ERROR: /build/app/outputs/bundle/release/app.aab
##[error]Process completed with exit code 2.
```
Does the app still work? If yes, could you help me with correcting my error if I did something wrong with arguments?

**Comment by rakeshgirase** [comment]
Hi @CukierPuder420, it does work. You are trying to upload the aab file but passing the parameter as apk file. May be that is the reason. Correct the parameters and try again. Let me know how it goes.

**Comment by jakubkrapiec** [comment]
Hi,
after a few trials I managed to work it out, but a proper documentation would be really helpful here :)
To the future generations: command for uploading .aab appbundle looks like that:
`java -jar release-manager-1.1.jar -key "my-api-key.json" -file "directory/of/my/app.aab" -track "internal" -name "MyAppName" -notes "update notes" -packageName my.package.name`
Thank you for support & have a nice evening 💜

**Comment by rakeshgirase** [comment]
Thank you. I have corrected my release notes.
